In [1]:
import pandas as pd
from sqlalchemy import create_engine

#### Eliza's Section

#### Lora's Section

In [2]:
#load in coffee data and create pandas datafile
coffee_file = "Resources/domestic-consumption.csv"
coffee_df = pd.read_csv(coffee_file)
coffee_df.head(100)

,domestic_consumption,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Angola,20.000,30.000,35.000,20.000,25.000,10.000,20.000,40.000,30.000,...,30.000,30.000,30.000,30.000,30.000,30.000,30.000,30.0000,30.000,30.000
1,Bolivia (Plurinational State of),25.000,27.000,27.500,28.500,29.500,30.500,31.500,32.500,33.000,...,46.000,47.500,49.000,50.500,52.000,53.500,55.000,57.0000,58.500,60.000
2,Brazil,8200.000,8500.000,8900.000,9100.000,9300.000,10100.000,11000.000,11500.000,12200.000,...,18390.000,19132.000,19720.000,20330.000,20085.000,20333.000,20508.000,21225.0000,21997.000,22250.000
3,Burundi,2.000,1.600,1.700,1.910,2.000,2.000,2.000,2.000,2.000,...,1.399,2.000,2.000,2.000,2.000,2.000,2.000,2.0000,2.000,2.000
4,Ecuador,350.000,350.000,350.000,350.000,350.000,350.000,300.000,300.000,300.000,...,150.000,150.000,150.000,150.000,155.000,155.000,155.000,155.0000,155.000,155.000
5,Indonesia,1242.000,1280.000,1319.000,1359.000,1400.000,1443.000,1486.000,1532.000,1578.000,...,3333.000,3333.000,3667.000,3900.000,4250.000,4417.000,4550.000,4650.0000,4750.000,4800.000
6,Madagascar,350.000,300.000,350.000,360.000,166.666,167.000,167.000,167.000,167.000,...,467.000,467.000,450.000,430.000,410.000,390.000,370.000,360.0000,365.000,375.000
7,Malawi,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.0000,1.000,1.000
8,Papua New Guinea,3.000,3.000,3.000,2.000,2.000,2.000,2.000,2.000,1.000,...,2.000,1.430,1.236,1.711,2.039,1.924,1.800,2.0000,2.000,2.000
9,Paraguay,15.000,15.000,15.000,20.000,20.000,20.000,20.000,20.000,20.000,...,20.000,20.000,20.000,20.000,20.000,20.000,20.000,20.0000,20.000,20.000
10,Peru,190.000,190.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,...,250.000,250.000,250.000,250.000,250.000,250.000,250.000,250.0000,250.000,250.000
11,Rwanda,1.000,1.000,1.000,1.000,1.000,1.000,1.000,3.000,3.000,...,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.0000,1.000,1.000
12,Timor-Leste,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.490,0.490,0.490,0.490,0.490,0.490,0.4900,0.490,0.490
13,Zimbabwe,8.000,8.000,8.000,8.333,8.333,6.600,4.000,4.000,4.000,...,4.000,4.000,4.000,4.000,4.000,4.000,4.000,4.0000,4.000,4.000
14,Congo,3.000,2.667,2.667,3.000,3.000,3.000,3.000,3.000,3.000,...,3.000,3.000,3.000,3.000,3.000,3.000,3.000,3.0000,3.000,3.000
15,Cuba,213.000,213.000,195.000,194.100,194.000,194.000,189.000,195.000,200.000,...,220.000,220.000,220.000,220.000,220.000,220.000,220.000,220.0000,220.000,220.000
16,Dominican Republic,320.000,320.000,320.000,320.000,330.000,350.000,325.000,325.000,325.000,...,378.000,378.000,378.000,378.000,383.333,388.000,388.000,390.0000,390.000,390.000
17,Haiti,220.000,330.000,330.000,330.000,330.000,330.000,330.000,330.000,330.000,...,340.000,340.000,340.000,340.000,340.000,340.000,340.000,340.0000,340.000,345.000
18,Philippines,720.000,750.000,750.000,770.000,790.000,810.000,831.000,853.000,810.000,...,1820.000,2125.000,2175.000,2325.000,2550.000,2800.000,3000.000,3030.0000,3180.000,3300.000
19,Tanzania,4.000,3.500,19.200,17.500,17.500,13.600,16.600,17.000,17.000,...,47.000,47.000,58.950,71.700,73.467,76.717,92.050,91.3000,91.667,92.000
20,Zambia,1.500,1.500,1.432,1.000,1.500,0.600,1.000,0.600,0.600,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000
21,Benin,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000
22,Cameroon,83.300,83.333,83.333,100.000,100.000,100.000,100.000,100.000,100.000,...,69.000,68.333,70.017,71.733,73.483,75.317,76.000,77.0000,78.000,78.000
23,Central African Republic,28.000,28.000,28.000,25.000,15.000,10.000,10.000,10.000,19.000,...,8.333,10.000,13.333,16.667,20.000,20.000,20.000,20.0000,20.000,20.000
24,Colombia,1235.000,1269.000,1303.000,1339.000,1375.000,1359.000,1343.000,1328.000,1312.000,...,1274.479,1311.024,1435.065,1514.242,1617.020,1665.451,1720.373,1736.4414,1793.271,1791.410
25,Costa Rica,375.000,375.000,375.000,375.000,375.000,375.000,375.000,375.000,375.000,...,295.441,407.221,380.888,423.097,335.060,380.742,448.821,329.4570,353.334,365.000
26,Côte d'Ivoire,50.000,50.000,50.000,50.000,50.000,50.000,50.000,50.000,50.000,...,317.000,317.000,317.000,317.000,317.000,317.000,317.000,317.0000,317.000,317.000
27,Democratic Republic of Congo,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.000,...,200.000,200.000,200.000,200.000,200.000,200.000,200.000,200.0000,200.000,200.000
28,El Salvador,180.000,180.000,230.000,230.000,230.000,270.000,230.000,191.667,191.667,...,268.300,276.000,273.400,276.600,275.000,280.000,285.000,292.0000,300.000,300.000
29,Equatorial Guinea,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000
30,Ethiopia,1200.000,1264.000,1331.000,1402.000,1476.000,1555.000,1637.000,1724.000,1816.000,...,3210.000,3383.000,3383.000,3400.000,3550.000,3625.000,3700.000,3725.0000,3750.000,3800.000
31,Gabon,1.700,1.000,0.800,0.800,1.000,0.800,0.833,0.800,0.800,...,0.250,0.947,1.032,0.967,0.583,0.517,0.500,0.5000,0.500,0.500
32,Ghana,17.000,17.000,17.000,17.000,28.000,28.000,3.000,3.000,1.000,...,2.000,2.000,2.000,2.000,2.000,2.000,2.000,2.0000,2.000,2.000
33,Guatemala,300.000,300.000,300.000,310.000,310.000,310.000,300.000,300.000,300.000,...,320.000,340.000,350.000,360.000,370.000,380.000,390.000,390.0000,395.000,395.000
34,Guinea,25.000,25.000,62.500,33.000,50.000,50.000,50.000,50.000,50.000,...,50.000,50.000,50.000,50.000,50.000,50.000,50.000,50.0000,50.000,50.000
35,Guyana,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,4.867,...,8.233,8.500,8.600,8.700,8.800,8.900,9.000,9.0000,9.000,9.000
36,Honduras,188.154,257.100,240.000,230.000,253.000,161.000,167.924,161.000,138.000,...,306.667,335.000,340.000,345.000,350.000,355.000,365.000,370.0000,375.000,375.000
37,India,903.000,916.667,917.000,833.333,835.000,837.000,838.000,839.000,900.000,...,1325.000,1325.000,1325.000,1375.000,1400.000,1430.000,1450.000,1440.0000,1470.000,1475.000
38,Jamaica,7.000,11.000,6.000,9.600,15.000,15.000,18.000,20.000,14.800,...,9.000,9.000,9.000,9.000,9.000,9.000,9.000,9.0000,9.000,9.000
39,Kenya,50.000,50.000,50.000,50.000,50.000,50.000,50.000,50.000,50.000,...,50.000,50.000,50.000,50.000,55.000,55.000,60.000,60.0000,65.000,70.000
40,Lao People's Democratic Republic,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,150.000,150.000,150.000,150.000,150.000,150.000,150.000,150.0000,155.000,155.000
41,Liberia,3.000,3.000,3.000,5.000,5.000,5.000,5.000,5.000,5.000,...,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.0000,5.000,5.000
42,Mexico,1374.000,1200.000,1300.000,1070.000,1020.000,1179.000,1235.000,1201.000,1108.000,...,2200.000,2354.000,2354.000,2354.000,2321.000,2347.000,2329.000,2360.0000,2400.000,2450.000
43,Nepal,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000
44,Nicaragua,34.000,138.000,65.600,108.900,89.600,111.500,95.370,123.000,126.500,...,196.622,202.745,205.261,207.864,209.561,211.742,213.946,216.7280,218.000,220.000
45,Nigeria,27.500,35.750,35.750,40.000,40.000,40.000,40.000,40.000,40.000,...,40.000,40.000,40.000,40.000,40.000,40.000,40.000,40.0000,40.000,40.000
46,Panama,63.000,67.000,67.000,67.000,76.667,76.667,76.667,80.615,67.000,...,67.000,67.000,67.000,67.000,67.000,67.000,67.000,67.0000,67.000,67.000
47,Sierra Leone,9.000,9.000,9.000,5.000,5.000,8.000,8.000,5.000,5.000,...,5.000,5.000,5.000,5.000,5.000,5.000,5.000,5.0000,5.000,5.000
48,Sri Lanka,66.667,67.000,28.000,20.000,20.000,20.000,20.000,20.000,30.000,...,30.000,35.000,35.000,35.000,35.000,35.000,35.000,35.0000,35.000,35.000
49,Thailand,188.000,220.000,233.000,250.000,283.000,417.000,333.000,390.000,433.000,...,700.000,775.000,1100.000,1130.000,1200.000,1250.000,1300.000,1350.0000,1375.000,1400.000
50,Togo,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,2.000,...,2.000,2.000,0.210,0.242,0.238,0.195,0.220,0.2540,0.254,0.254
51,Trinidad & Tobago,8.000,11.500,10.000,10.000,14.000,14.000,14.000,14.000,14.000,...,11.000,10.000,10.000,10.000,10.000,10.000,10.000,10.0000,10.000,10.000
52,Uganda,70.000,75.000,75.000,75.000,80.000,80.000,80.000,101.190,116.000,...,188.700,204.000,210.000,216.000,220.800,229.200,234.000,240.0000,244.800,250.000
53,Venezuela,782.390,815.480,849.970,885.930,923.400,962.460,1003.180,1045.610,1089.840,...,1650.000,1650.000,1650.000,1650.000,1650.000,1650.000,1650.000,1650.0000,1600.000,1550.000
54,Viet Nam,150.000,230.000,250.000,267.000,267.000,281.845,297.516,314.058,331.519,...,1208.000,1583.000,1650.000,1825.000,2000.000,2200.000,2300.000,2400.0000,2500.000,2700.000
55,Yemen,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,130.000,130.000,130.000,130.000,130.000,125.000,115.000,100.0000,90.000,65.000

In [3]:
coffee_df_2016 = coffee_df[['domestic_consumption', '2016']].copy()
coffee_df_2016.head()

               domestic_consumption     2016
0                            Angola     30.0
1  Bolivia (Plurinational State of)     57.0
2                            Brazil  21225.0
3                           Burundi      2.0
4                           Ecuador    155.0

In [4]:
coffee_df_2016.rename(columns={"domestic_consumption" : "Country", "2016" : "Coffee_Consumption"}, inplace=True)
coffee_df_2016.head()

                            Country  Coffee_Consumption
0                            Angola                30.0
1  Bolivia (Plurinational State of)                57.0
2                            Brazil             21225.0
3                           Burundi                 2.0
4                           Ecuador               155.0

In [5]:
#load in happy and beers data and create pandas datafile
HappinessAlcohol_file = "Resources/HappinessAlcoholConsumption.csv"
HappinessAlcohol_df = pd.read_csv(HappinessAlcohol_file)
HappinessAlcohol_df.head()

,Country,Region,Hemisphere,HappinessScore,HDI,GDP_PerCapita,Beer_PerCapita,Spirit_PerCapita,Wine_PerCapita
0,Denmark,Western Europe,north,7.526,928,53.579,224,81,278
1,Switzerland,Western Europe,north,7.509,943,79.866,185,100,280
2,Iceland,Western Europe,north,7.501,933,60.530,233,61,78
3,Norway,Western Europe,north,7.498,951,70.890,169,71,129
4,Finland,Western Europe,north,7.413,918,43.433,263,133,97

#### Stephen's Section

#### Nathan's Section